---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: <<APP_NAME>>
    version: <<APP_NAME>>-<<ENV_NAME>>-<<TYPE>>
  name: <<APP_NAME>>-<<ENV_NAME>>-<<TYPE>>
  namespace: <<APP_GROUP>>-<<ENV_NAME>>
spec:
  ports:
    -
      name: http
      port: 80
      protocol: TCP
      targetPort: <<CONTAINER_PORT>>
  selector:
    version: <<APP_NAME>>-<<ENV_NAME>>-<<BUILD_NUMBER>>

