---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: <<APP_NAME>>
    version: <<APP_NAME>>-<<ENV_NAME>>-<<TYPE>>
  name: azure-load-balancer
  namespace: <<APP_GROUP>>-<<ENV_NAME>>
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: <<RESOURCE_GROUP>>
spec:
  loadBalancerIP: <<PUBLIC_IP>>
  type: LoadBalancer
  ports:
    -
      name: http
      port: 80
      protocol: TCP
      targetPort: <<CONTAINER_PORT>>
  selector:
    version: <<APP_NAME>>-<<ENV_NAME>>-<<BUILD_NUMBER>>

